.TH PYZORD 1 "10 Oct 2002"
.SH NAME
pyzord \- spam\-catching server
.SH SYNOPSIS
\fBpyzord\fP [\fB\-d\fP] [\fB\-\-homedir\fP \fIdir\fP]

Note: pyzord does not daemonize itself.

Note: logging information is written to standard output.

.SH OPTIONS
.TP
\fB\-d\fP
Turn on debugging
.TP
\fB\-\-homedir\fP \fIdir\fP
use dir as the home directory for Pyzor instead of the default ~/.pyzor.
See the files section for more information on what files are inside of the
homedir.
.SH FILES
\fI~/.pyzor/config\fP

The format of this file is INI-style (name=value, divided into [sections]).
Names are case insensitive. All values which are filenames can have
shell\-style tildes (~) in them. All values which are relative filenames are
interpreted to be relative to the Pyzor homedir.

\fBDefaults\fP
 [server]
 Port = 24441
 ListenAddress = 0.0.0.0
 DigestDB   = pyzord.db
 PasswdFile = pyzord.passwd
 AccessFile = pyzord.access
.SH SEE ALSO
pyzor(1)
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam
<calvin@debian.org> for the Debian distribution of pyzor but may be used
by others.
.BR
The main author of pyzor is Frank J. Tobin <ftobin@neverending.org>.  The
main project page for pyzor can be found at
http://sourceforge.net/projects/pyzor
