#!/bin/bash
set -evx

if [ `python -c 'import platform; print platform.python_implementation()'` = 'PyPy' ]
then
	pip install redis
	python setup.py install
elif [ `python -c 'import sys; print(sys.version_info[0])'` = '3' ]
then
	pip install redis
	python setup.py install
	2to3 -w . ./scripts/*
else
	sudo apt-get update -qq
	sudo apt-get install -y build-essential python-dev libmysqlclient-dev
	pip install -r requirements.txt
	python setup.py install
	mysql -e 'create database pyzor_test'
fi

python setup.py test




