#!/bin/bash
set -ev

pip install pytest pytest-cov python-coveralls

if [ `python -c 'import sys; print(sys.version_info[0])'` = '3' ]
then
	pip install redis
	python setup.py install
	2to3 -w . ./scripts/pyzor ./scripts/pyzord ./scripts/pyzor-migrate
else
	sudo apt-get update -qq
	sudo apt-get install -y build-essential python-dev libmysqlclient-dev
	pip install -r requirements.txt
	python setup.py install
	mysql -e 'create database pyzor_test'
fi

if [ "$1" != "prepare" ]
then
	py.test tests/unit/ --cov coveralls --cov-report term-missing
	py.test tests/functional/
fi


